[package]
name = "backup-agent"
version = "0.1.0"
authors = ["Chris MacNaughton <chmacnaughton@gmail.com>"]

[dependencies]
gj = "0.2"
gjio = "0.1"
capnp = "0.7"
capnp-rpc = "0.7"
backup-capnp = {git = "https://github.com/ChrisMacNaughton/backup_capnp.git"}